server:
  port: 8080

# 开启降级feign.hystrix
feign:
  hystrix:
    enabled: true

  #配置Eureka
eureka:
  client:
    service-url:
      # 注册中心地址7001-7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false  #不向EureKa注册自己